#!/usr/bin/env python3
"""Rebuild the original seven Metal effects from the preserved WebGL sources.

Run only when intentionally refreshing the port. The app ships the generated
Metal source and has no JavaScript, Python, or WebGL runtime dependency.
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
shared = (root / 'src/gl/shared.ts').read_text()
prelude = shared.split('export const PRELUDE = `')[1].split('`;')[0]
uniforms = re.findall(r'uniform (float|vec2) (u_\w+);', prelude)
macros = []
index = 0
for kind, name in uniforms:
    if kind == 'vec2':
        macros.append(f'#define {name} float2(uniforms[{index}], uniforms[{index+1}])')
        index += 2
    else:
        macros.append(f'#define {name} uniforms[{index}]')
        index += 1

def metal(source):
    source = re.sub(r'/\*.*?\*/', '', source, flags=re.S)
    source = re.sub(r'//[^\n]*', '', source)
    for size in (2, 3, 4):
        source = source.replace(f'vec{size}', f'float{size}')
    source = re.sub(r'mat2\(([^,]+),([^,]+),([^,]+),([^\)]+)\)',
                    r'float2x2(float2(\1,\2), float2(\3,\4))', source)
    source = source.replace('mat2', 'float2x2')
    source = source.replace('atan(p.y, p.x)', 'atan2(p.y, p.x)')
    source = re.sub(r'\bmod\(', 'glmod(', source)
    source = source.replace('texture(u_spectrum,', 'spectrum.sample(spectrumSampler,')
    source = source.replace('texture(u_history,', 'historyTexture.sample(historySampler,')
    # GLSL defines reversed-edge smoothsteps used by the original effects.
    source = re.sub(r'\bsmoothstep\(', 'smoothStep(', source)
    return re.sub(r'\n\s*\n\s*\n', '\n\n', source)

palette_source = (root / 'src/gl/palettes.ts').read_text()
hexes = re.findall(r'"(#[0-9a-f]{6})"', palette_source.split('function toVec3')[0])
colors = []
for value in hexes:
    n = int(value[1:], 16)
    colors.append('float3(' + ', '.join(f'{((n >> b) & 255)/255:.6f}' for b in (16, 8, 0)) + ')')
palette = '''
float3 rampAt(float world, float t) {
    if (world < 0.5) return nativeRamp(t);
    int base = clamp(int(world) - 1, 0, 11) * 4;
    float x = clamp(t, 0.0, 1.0) * 3.0;
    int stop = min(int(x), 2);
    return mix(paletteStops[base + stop], paletteStops[base + stop + 1], x - float(stop));
}
float3 world(float t) {
    t = clamp(t, 0.0, 1.0);
    return mix(rampAt(u_palette, t), rampAt(u_paletteTo, t), u_paletteMix);
}
'''
names = ['veil', 'bloom', 'coil', 'ink', 'harp', 'fathom', 'quicksilver']
body = metal(prelude[prelude.index('#define PI'):].replace('${PALETTE_GLSL}', '')) + palette
for name in names:
    source = (root / f'src/gl/presets/{name}.ts').read_text().split(f'export const {name} = `')[1].rsplit('`;', 1)[0]
    body += '\n' + metal(source).replace('float3 scene(', f'float3 {name}(')
body += '\nfloat3 scene(int effect, float2 uv, float2 st) {\n switch(effect) {\n'
body += '\n'.join(f'case {i}: return {name}(uv, st);' for i, name in enumerate(names))
body += '\ndefault: return veil(uv, st);\n}\n}\n'
post = shared.split('export const EPILOGUE = `')[1].split('`;')[0]
post = post.replace('void main()', 'float4 render(float2 position, int effect)')
post = post.replace('gl_FragCoord.xy', 'position').replace('scene(uv, st)', 'scene(effect, uv, st)')
post = post.replace('outColor =', 'return')
body += metal(post)
source = '''// Generated by scripts/port-metal.py. Native Metal; no WebGL runtime.
#include <metal_stdlib>
using namespace metal;
constant float3 paletteStops[] = {
''' + ',\n'.join(colors) + '''
};
constexpr sampler spectrumSampler(coord::normalized, address::clamp_to_edge, filter::linear);
constexpr sampler historySampler(coord::normalized, s_address::clamp_to_edge, t_address::repeat, filter::linear);
float glmod(float x, float y) { return x - y * floor(x / y); }
float smoothStep(float a, float b, float x) {
    float t = clamp((x - a) / (b - a), 0.0f, 1.0f);
    return t * t * (3.0f - 2.0f * t);
}
''' + '\n'.join(macros) + '''
struct Instrument {
    constant float* uniforms;
    texture2d<float> spectrum;
    texture2d<float> historyTexture;
''' + body + '''
};
struct VertexOut { float4 position [[position]]; };
vertex VertexOut fullScreen(uint id [[vertex_id]]) {
    float2 p = float2((id << 1) & 2, id & 2);
    return {float4(p * 2.0 - 1.0, 0.0, 1.0)};
}
fragment float4 visualizer(VertexOut in [[stage_in]],
                           constant float* uniforms [[buffer(0)]],
                           constant int& effect [[buffer(1)]],
                           texture2d<float> spectrum [[texture(0)]],
                           texture2d<float> historyTexture [[texture(1)]]) {
    Instrument instrument {uniforms, spectrum, historyTexture};
    return instrument.render(float2(in.position.x, uniforms[1] - in.position.y), effect);
}
'''
destination = root / 'native/Sources/Serein/Resources/Effects.metal'
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text('\n'.join(line.rstrip() for line in source.splitlines()) + '\n')
print(f'Wrote {destination}: {index} uniform floats, {len(names)} effects')
