// Generated by scripts/port-metal.py. Native Metal; no WebGL runtime.
#include <metal_stdlib>
using namespace metal;
constant float3 paletteStops[] = {
float3(0.039216, 0.011765, 0.015686),
float3(0.878431, 0.203922, 0.101961),
float3(0.909804, 0.760784, 0.164706),
float3(0.247059, 0.658824, 0.847059),
float3(0.003922, 0.027451, 0.058824),
float3(0.121569, 0.435294, 0.815686),
float3(0.784314, 0.878431, 0.290196),
float3(0.878431, 0.376471, 0.564706),
float3(0.011765, 0.015686, 0.054902),
float3(0.290196, 0.294118, 0.752941),
float3(0.815686, 0.372549, 0.627451),
float3(0.909804, 0.815686, 0.439216),
float3(0.039216, 0.015686, 0.101961),
float3(0.478431, 0.184314, 0.815686),
float3(0.878431, 0.313725, 0.541176),
float3(0.498039, 0.847059, 0.752941),
float3(0.019608, 0.023529, 0.062745),
float3(0.184314, 0.372549, 0.690196),
float3(0.878431, 0.439216, 0.250980),
float3(0.847059, 0.815686, 0.376471),
float3(0.070588, 0.011765, 0.047059),
float3(0.815686, 0.156863, 0.376471),
float3(0.941176, 0.627451, 0.250980),
float3(0.376471, 0.752941, 0.690196),
float3(0.007843, 0.062745, 0.035294),
float3(0.101961, 0.541176, 0.376471),
float3(0.815686, 0.784314, 0.250980),
float3(0.690196, 0.376471, 0.815686),
float3(0.019608, 0.047059, 0.023529),
float3(0.290196, 0.603922, 0.227451),
float3(0.847059, 0.815686, 0.250980),
float3(0.878431, 0.407843, 0.313725),
float3(0.003922, 0.031373, 0.047059),
float3(0.101961, 0.478431, 0.564706),
float3(0.878431, 0.415686, 0.188235),
float3(0.690196, 0.658824, 0.878431),
float3(0.039216, 0.023529, 0.015686),
float3(0.627451, 0.250980, 0.094118),
float3(0.878431, 0.627451, 0.250980),
float3(0.372549, 0.690196, 0.878431),
float3(0.015686, 0.023529, 0.101961),
float3(0.352941, 0.125490, 0.627451),
float3(0.815686, 0.188235, 0.439216),
float3(0.941176, 0.690196, 0.250980),
float3(0.019608, 0.011765, 0.058824),
float3(0.313725, 0.125490, 0.627451),
float3(0.133333, 0.658824, 0.415686),
float3(0.909804, 0.815686, 0.376471)
};
constexpr sampler spectrumSampler(coord::normalized, address::clamp_to_edge, filter::linear);
constexpr sampler historySampler(coord::normalized, s_address::clamp_to_edge, t_address::repeat, filter::linear);
float glmod(float x, float y) { return x - y * floor(x / y); }
float smoothStep(float a, float b, float x) {
    float t = clamp((x - a) / (b - a), 0.0f, 1.0f);
    return t * t * (3.0f - 2.0f * t);
}
#define u_resolution float2(uniforms[0], uniforms[1])
#define u_time uniforms[2]
#define u_flow uniforms[3]
#define u_motion uniforms[4]
#define u_seed uniforms[5]
#define u_alpha uniforms[6]
#define u_palette uniforms[7]
#define u_paletteTo uniforms[8]
#define u_paletteMix uniforms[9]
#define u_grain uniforms[10]
#define u_level uniforms[11]
#define u_sub uniforms[12]
#define u_bass uniforms[13]
#define u_lowMid uniforms[14]
#define u_mid uniforms[15]
#define u_high uniforms[16]
#define u_air uniforms[17]
#define u_centroid uniforms[18]
#define u_noise uniforms[19]
#define u_flux uniforms[20]
#define u_kick uniforms[21]
#define u_snare uniforms[22]
#define u_hat uniforms[23]
#define u_pulse uniforms[24]
#define u_beat uniforms[25]
#define u_beatTime uniforms[26]
#define u_dynamics uniforms[27]
#define u_swell uniforms[28]
#define u_silence uniforms[29]
#define u_section uniforms[30]
#define u_historyRow uniforms[31]
struct Instrument {
    constant float* uniforms;
    texture2d<float> spectrum;
    texture2d<float> historyTexture;
#define PI 3.141592653589793
#define TAU 6.283185307179586

float hash11(float p) {
  p = fract(p * 0.1031);
  p *= p + 33.33;
  return fract(p * (p + p));
}

float hash21(float2 p) {
  p = fract(p * float2(123.34, 456.21));
  p += dot(p, p + 45.32 + u_seed);
  return fract(p.x * p.y);
}

float2 hash22(float2 p) {
  float3 a = fract(float3(p.xyx) * float3(0.1031, 0.1030, 0.0973) + u_seed * 0.017);
  a += dot(a, a.yzx + 33.33);
  return fract((a.xx + a.yz) * a.zy);
}

float noise(float2 p) {
  float2 i = floor(p);
  float2 f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  return mix(mix(hash21(i), hash21(i + float2(1.0, 0.0)), f.x),
             mix(hash21(i + float2(0.0, 1.0)), hash21(i + float2(1.0)), f.x), f.y);
}

float fbm(float2 p) {
  float value = 0.0;
  float amp = 0.5;
  float2x2 rot = float2x2(float2(0.82, -0.57), float2( 0.57, 0.82));
  for (int i = 0; i < 5; i++) {
    value += amp * noise(p);
    p = rot * p * 2.03 + 1.7;
    amp *= 0.5;
  }
  return value;
}

float fbm3(float2 p) {
  float value = 0.0;
  float amp = 0.5;
  float2x2 rot = float2x2(float2(0.82, -0.57), float2( 0.57, 0.82));
  for (int i = 0; i < 3; i++) {
    value += amp * noise(p);
    p = rot * p * 2.11 + 1.3;
    amp *= 0.5;
  }
  return value;
}

float2x2 rot2(float a) {
  float s = sin(a);
  float c = cos(a);
  return float2x2(float2(c, -s), float2( s, c));
}

float spow(float x, float k) {
  return pow(max(x, 1e-6), k);
}

float gauss(float x) {
  return exp(-x * x);
}

float3 spectralHue(float turn) {
  float3 c = 0.5 + 0.5 * cos(TAU * (turn + float3(0.0, 0.33, 0.67)));

  return c / max(max(max(c.r, c.g), c.b), 1e-4);
}

float3 nativeRamp(float t) {
  float turn = fract(u_seed * 0.137 + 0.08);
  float3 shadow = float3(0.022, 0.018, 0.026);
  float3 first = spectralHue(turn);
  float3 second = spectralHue(turn + 0.34);
  float3 third = spectralHue(turn + 0.66);
  if (t < 0.3333) return mix(shadow, first, t * 3.0);
  if (t < 0.6666) return mix(first, second, (t - 0.3333) * 3.0);
  return mix(second, third, (t - 0.6666) * 3.0);
}

float line(float d, float width) {
  return 1.0 - smoothStep(width, width + 0.012, abs(d));
}

float spec(float x) {
  return spectrum.sample(spectrumSampler, float2(clamp(x, 0.0, 1.0), 0.25)).r;
}

float specSlow(float x) {
  return spectrum.sample(spectrumSampler, float2(clamp(x, 0.0, 1.0), 0.75)).r;
}

float specHz(float hz) {
  return spec(log(clamp(hz, 28.0, 16000.0) / 28.0) / log(16000.0 / 28.0));
}

float specSpread(float x) {
  return (specSlow(x - 0.070) + specSlow(x - 0.035) + specSlow(x)
        + specSlow(x + 0.035) + specSlow(x + 0.070)) * 0.2;
}

float specWide(float x) {
  return (spec(x - 0.06) + spec(x - 0.03) + spec(x)
        + spec(x + 0.03) + spec(x + 0.06)) * 0.2;
}

float specBands(float x) {
  float f = clamp(x, 0.0, 1.0) * 5.0;
  float i = min(floor(f), 4.0);
  float w = smoothStep(0.0, 1.0, f - i);
  return mix(specSpread(0.06 + i * 0.176), specSpread(0.06 + (i + 1.0) * 0.176), w);
}

float specBandsFast(float x) {
  float f = clamp(x, 0.0, 1.0) * 5.0;
  float i = min(floor(f), 4.0);
  float w = smoothStep(0.0, 1.0, f - i);
  return mix(specWide(0.06 + i * 0.176), specWide(0.06 + (i + 1.0) * 0.176), w);
}

float power() {
  return clamp(smoothStep(0.505, 0.605, u_dynamics) * 0.50
             + smoothStep(0.480, 0.920, u_level) * 0.50, 0.0, 1.0);
}

float history(float x, float age) {
  float row = glmod(u_historyRow - age * 255.0, 256.0);
  return historyTexture.sample(historySampler, float2(clamp(x, 0.0, 1.0), (row + 0.5) / 256.0)).r;
}

float3 ramp[4];
float3 rampStop(float world, int stop) {
    if (world < 0.5) return nativeRamp(float(stop) / 3.0);
    return paletteStops[clamp(int(world) - 1, 0, 11) * 4 + stop];
}
void preparePalette() {
    for (int stop = 0; stop < 4; stop++)
        ramp[stop] = mix(rampStop(u_palette, stop), rampStop(u_paletteTo, stop), u_paletteMix);
}
float3 world(float t) {
    float x = clamp(t, 0.0, 1.0) * 3.0;
    return ramp[0] + (ramp[1] - ramp[0]) * clamp(x, 0.0, 1.0)
         + (ramp[2] - ramp[1]) * clamp(x - 1.0, 0.0, 1.0)
         + (ramp[3] - ramp[2]) * clamp(x - 2.0, 0.0, 1.0);
}


float3 veil(float2 uvIn, float2 st) {
  float2 uv = uvIn * 2.0;
  float t = u_time;
  float2 p = rot2(-0.12) * uv;

  float warp = fbm(p * (1.38 + u_mid * 0.55) + float2(t * 0.045, u_seed));
  float warp2 = fbm(p * 2.45 - float2(t * 0.03, u_seed * 0.7));

  float y = p.y
    + (warp - 0.5) * (0.48 + u_bass * 0.52)
    + sin(p.x * 2.2 + t * 0.35) * (0.06 + u_sub * 0.09);
  y += sin(p.x * 8.0 - t * 2.4) * u_flux * 0.025;

  float membrane = line(y, 0.018 + u_level * 0.034 + u_pulse * 0.018);
  float filament = line(y + 0.19 + (warp2 - 0.5) * 0.20, 0.005 + u_air * 0.018);
  float echo = line(y - 0.20 + sin(p.x * 3.4 - t) * 0.07, 0.004 + u_mid * 0.01);
  float haze = exp(-4.6 * abs(y));
  float sideFade = smoothStep(1.55, 0.05, abs(p.x));

  float3 ember = world(0.20);
  float3 lilac = world(0.48);
  float3 ice = world(0.74);
  float3 echoTone = world(1.00);
  float3 spectral = mix(ember, lilac, smoothStep(-0.8, 0.9, p.x + warp));

  float3 col = float3(0.022, 0.021, 0.019);
  col = mix(col, spectral, membrane * sideFade);
  col += filament * ice * (0.45 + u_air * 0.55) * sideFade;
  col += echo * echoTone * (0.18 + u_flux * 0.5) * sideFade;
  col += haze * spectral * (0.06 + u_level * 0.20 + u_pulse * 0.14) * sideFade;

  return col;
}

float3 bloom(float2 uv, float2 st) {
  float t = u_flow;

  float2 p = uv;
  p *= rot2(t * 0.008);

  float r = length(p);
  float ang = atan2(p.y, p.x);
  float2 outward = p / max(r, 1e-4);

  float2 lightDir = normalize(float2(-0.55, 0.84));

  float3 col = float3(0.0);
  float outermost = 0.0;

  const int RINGS = 4;
  float cycle = u_beatTime * 0.25;

  for (int i = 0; i < RINGS; i++) {
    float fi = float(i);
    float age = (fract(cycle) + fi) / float(RINGS);

    float birth = floor(cycle) - fi;
    float ident = fract(birth * 0.381) * 6.283;
    float grain = hash11(birth * 0.117);

    float radius = spow(age, 0.78) * (0.46 + u_swell * 0.30);

    float wobble =
        sin(ang * 2.0 + t * 0.09 + ident + u_seed) * 0.52
      + sin(ang * 3.0 - t * 0.06 + ident * 1.7) * 0.31
      + sin(ang * 5.0 + t * 0.04 + ident * 0.6) * 0.17;
    float edge = radius * (1.0 + wobble * (0.05 + age * 0.30));
    outermost = max(outermost, edge);

    float thickness = 0.018 + age * 0.085 + u_bass * 0.016;
    float d = abs(r - edge);

    float shell = exp(-spow(d / thickness, 1.45));
    float diffuse = exp(-d / (thickness * 2.8));
    float fade = spow(1.0 - age, 1.7);

    float lambert = 0.34 + 0.66 * (0.5 + 0.5 * dot(outward, lightDir));

    float3 tone = world(0.94 - age * 0.60 + u_centroid * 0.10 - grain * 0.16 + u_section * 0.06);

    float charge = 0.45 + u_section * 0.60;
    col += tone * shell * fade * lambert * (0.32 + u_level * 0.52) * charge;
    col += tone * diffuse * fade * (0.06 + u_level * 0.14 + u_section * 0.05);

    float inside = smoothStep(edge, edge * 0.35, r);
    float stain = fbm(p * (1.9 + age * 1.6) + float2(ident * 2.4 + u_seed, -t * 0.03));
    col += tone * inside * fade * fade * spow(stain, 1.7) * lambert * (0.18 + u_mid * 0.38) * charge;

    float crest = gauss((r - edge) / (thickness * 0.55));
    col += world(0.98) * crest * fade * spow(lambert, 2.5) * (0.09 + u_snare * 0.32 + u_hat * 0.22);
  }

  col += world(0.99) * exp(-spow(r / (0.028 + u_kick * 0.012), 1.6)) * (0.16 + u_kick * 0.40);
  col += world(0.60) * exp(-r * 6.0) * (0.03 + u_level * 0.22 + u_pulse * 0.10);

  float wisp = fbm(p * (2.4 + u_centroid * 1.6) + float2(-t * 0.022, t * 0.014));
  float beyond = smoothStep(outermost * 0.85, outermost * 1.7, r) * exp(-r * 1.8);
  col += world(0.34 + u_centroid * 0.22) * spow(clamp(wisp, 0.0, 1.0), 2.6)
    * beyond * (0.16 + u_mid * 0.50) * (0.40 + u_section * 0.80);

  float depth = fbm(p * 1.3 + float2(t * 0.014, -t * 0.009));
  col += world(0.20 + u_centroid * 0.24) * spow(depth, 2.0)
    * (0.045 + u_swell * 0.16 + u_sub * 0.06 + u_section * 0.04);

  return col;
}


float segment(float2 p, float2 a, float2 b) {
  float2 pa = p - a;
  float2 ba = b - a;
  float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-6), 0.0, 1.0);
  return length(pa - ba * h);
}

float2 bodyAt(float s, float t, float lean) {
  float k1 = 0.48 + fract(u_seed * 0.317) * 0.55;
  float k2 = 0.80 + fract(u_seed * 0.713) * 0.70;
  float k3 = 1.90 + fract(u_seed * 0.191) * 1.60;
  float o1 = u_seed * 1.7;
  float o2 = u_seed * 2.3;

  float span = 3.4 + fract(u_seed * 0.107) * 2.2;
  float phase = s * span - t * 0.15;

  float2 c = float2(
    sin(phase * k1 + o1) * (1.02 + fract(u_seed * 0.53) * 0.28),
    sin(phase * k2 + o2) * (0.52 + fract(u_seed * 0.29) * 0.22)
  );
  c += float2(sin(phase * k3 + o1), cos(phase * (k3 + 0.8) + o2)) * (0.12 + lean * 0.10);

  c += float2(sin(t * 0.031 + o1) * 0.30, cos(t * 0.024 + o2) * 0.16);
  return c;
}

float3 coil(float2 uv, float2 st) {
  float t = u_flow;
  float2 p = uv * 2.35;
  p *= rot2(sin(t * 0.022) * 0.14);

  float3 col = float3(0.0);
  float nearest = 10.0;

  float lean = specSlow(0.10) * 0.5 + u_swell * 0.5;

  const int SEGMENTS = 46;
  float2 previous = bodyAt(0.0, t, lean);

  for (int i = 1; i <= SEGMENTS; i++) {
    float s = float(i) / float(SEGMENTS);

    float band = spow(specSlow(0.04 + s * 0.84), 1.2);
    float lit = spow(spec(0.04 + s * 0.84), 1.2);

    float2 here = bodyAt(s, t, lean);

    float taper = spow(sin(s * PI), 0.5);
    float knots = 0.86 + 0.14 * sin(s * 7.0 + u_seed * 3.0);
    float thickness = (0.024 + band * 0.080 + u_kick * 0.026 + u_sub * 0.020) * taper * knots + 0.002;

    float d = segment(p, previous, here);
    nearest = min(nearest, d);
    previous = here;

    float glow = thickness / (d + thickness * 0.70);
    float core = spow(glow, 3.6);
    float halo = spow(glow, 1.8);

    float3 tone = world(0.20 + s * 0.44 + lit * 0.34 + u_centroid * 0.14 + u_section * 0.12);
    col += tone * core * taper * (0.048 + lit * 0.17 + u_kick * 0.06) * (0.40 + u_section * 0.75);
    col += tone * halo * taper * (0.024 + lit * 0.075) * (0.35 + u_section * 0.75);
  }

  col += world(0.30) * exp(-nearest * 3.2) * (0.035 + u_level * 0.26 + u_pulse * 0.12 + u_section * 0.10);
  col += world(0.55) * exp(-nearest * 8.0) * (0.010 + u_snare * 0.22);

  float2 grid = p * 22.0;
  float2 id = floor(grid);
  float2 f = fract(grid) - 0.5;
  float2 h = hash22(id);
  float mote = smoothStep(0.09, 0.0, length(f - (h - 0.5) * 0.7)) * spow(h.x, 3.0);

  col += world(0.72) * mote * exp(-nearest * 2.0) * (0.10 + u_section * 0.45 + u_hat * 1.1);

  return col;
}


const float PUSH = 1.85;

float3 ink(float2 uv, float2 st) {
  float t = u_flow * 0.05;

  float breathe = 1.0 - u_pulse * 0.018 - u_kick * 0.012;
  float2 p = uv * 1.75 * breathe;
  p *= rot2(sin(u_flow * 0.012) * 0.08);

  float d = length(p);

  float2 drift = float2(t * 0.85, -t * 0.5);

  float2 q = float2(
    fbm3(p + drift),
    fbm3(p + drift.yx * 0.7 + 1.3)
  );

  float2 r = float2(
    fbm3(p + PUSH * q + float2(1.7, 9.2) + drift * 1.35),
    fbm3(p + PUSH * q + float2(8.3, 2.8) - drift * 1.05)
  );

  float density = fbm(p + 2.6 * r);

  float envelope = exp(-d * d * (2.15 - u_swell * 0.75 - u_section * 0.45));

  density = clamp((density - 0.30) * 2.7, 0.0, 1.0) * envelope;
  density = spow(density, 1.20);

  float shear = clamp(length(r - 0.5) * 2.2, 0.0, 1.0);

  float filament = spow(clamp(fbm3(p * 5.5 + r * 3.0 - t * 1.1), 0.0, 1.0), 5.0);

  float swirl = clamp(r.x * 0.90 + r.y * 0.40 - 0.12, 0.0, 1.0);
  float tone = clamp(
      0.04
    + swirl * 0.56
    + shear * 0.18
    + u_centroid * 0.26
    + u_section * 0.10
    + (1.0 - clamp(d, 0.0, 1.0)) * 0.12,
    0.0, 1.0);

  float3 col = world(tone) * density * (0.34 + u_level * 1.55 + u_kick * 0.45) * (0.45 + u_section * 0.60);
  col += world(0.90) * filament * density * (0.04 + u_air * 0.70 + u_hat * 0.50 + u_section * 0.25);

  float core = exp(-d * (4.4 - u_kick * 1.8 - u_swell * 0.7));
  col += world(0.97) * core * (0.10 + density * 0.55) * (0.08 + u_kick * 1.15 + u_pulse * 0.22);
  col += world(0.55) * exp(-d * 2.0) * density * (0.03 + u_sub * 0.42);

  float seam = gauss((density - 0.50) / 0.040);
  col += world(0.94) * seam * envelope * (u_snare * 0.55 + u_flux * 0.15);

  return col;
}

float3 harp(float2 uv, float2 st) {
  float t = u_flow;
  float2 p = uv;

  float3 col = float3(0.0);
  float height = clamp(p.y + 0.5, 0.0, 1.0);

  float hang = smoothStep(0.0, 0.10, height) * smoothStep(1.0, 0.90, height);
  float along = sin(clamp((height - 0.06) / 0.88, 0.0, 1.0) * PI);

  const int STRINGS = 16;
  for (int i = 0; i < STRINGS; i++) {
    float k = (float(i) + 0.5) / float(STRINGS);

    float band = spow(specSlow(0.04 + k * 0.86), 1.35);
    float lit = spow(spec(0.04 + k * 0.86), 1.35);

    float presence = smoothStep(0.12, 0.58, band);
    if (presence < 0.004) continue;

    float x0 = (k - 0.5) * 1.58;

    float excite = clamp(
      u_kick * smoothStep(0.62, 0.0, k)
      + u_snare * smoothStep(0.10, 0.62, k)
      + u_hat * smoothStep(0.55, 1.0, k) * 0.7,
      0.0, 1.0);

    float shape = sin(height * PI) * 0.86 + sin(height * TAU) * 0.14;
    float rate = (1.1 + k * 4.6) * (0.45 + u_motion * 0.75);
    float swing = sin(t * rate + float(i) * 1.7) * band * (0.008 + excite * 0.045);
    float x = x0 + shape * swing;

    float d = abs(p.x - x);
    float width = 0.0010 + band * 0.0022;
    float core = exp(-spow(d / width, 1.4));
    float glow = exp(-d * (90.0 - band * 45.0));
    float burn = 0.55 + lit * 0.85 + excite * 0.6;

    float3 tone = world(0.14 + k * 0.42 + lit * 0.36 + u_centroid * 0.08);
    col += tone * core * along * hang * presence * burn * (0.28 + band * 1.5);
    col += tone * glow * along * hang * presence * burn * (0.010 + band * 0.40);

    float strike = excite;
    float travel = fract(t * 0.55 + float(i) * 0.13);
    float bead = gauss((height - travel) / 0.055);
    col += world(0.98) * bead * exp(-d * 130.0) * strike * presence * 1.8;
  }

  float top = exp(-(1.0 - height) * 22.0);
  float bottom = exp(-height * 22.0);
  col += world(0.46 + u_centroid * 0.28) * (top + bottom)
    * (0.020 + u_level * 0.24 + u_pulse * 0.12 + u_section * 0.10);

  col += world(0.16) * fbm3(p * 1.8 + float2(t * 0.008, -t * 0.005)) * (0.014 + u_air * 0.060 + u_section * 0.020);

  return col;
}


float swell(float2 q, float2 dir, float k, float amp, float t) {
  return amp * sin(dot(q, dir) * k - t * sqrt(k) * 4.4);
}

float net(float2 q, float t, float3 band, float focus, float punch) {
  float lo = 0.45 + band.x * 1.10;
  float mid = 0.45 + band.y * 1.10;
  float hi = 0.45 + band.z * 1.10;

  float a0 = 1.00 * lo,  a1 = 0.82 * lo;
  float a2 = 0.62 * mid, a3 = 0.46 * mid;
  float a4 = 0.34 * hi;

  float f = swell(q, float2( 1.0000,  0.0000), 1.07, a0, t)
          + swell(q, float2( 0.9703,  0.2419), 1.63, a1, t)
          + swell(q, float2( 0.9816, -0.1908), 2.29, a2, t)
          + swell(q, float2( 0.9272,  0.3746), 3.11, a3, t)
          + swell(q, float2( 0.9455, -0.3256), 4.03, a4, t);
  f *= 3.0 / (a0 + a1 + a2 + a3 + a4);

  f += (noise(q * 0.40 + float2(-0.34, 0.94) * t * 4.00) - 0.5) * 2.30;
  f += (noise(q * 0.87 + float2( 0.71, 0.70) * t * 2.60) - 0.5) * 1.25;

  float bright = clamp(1.0 - abs(f) * (0.50 - punch * 0.115), 0.0, 1.0);
  float along = 0.30 + 0.70 * spow(0.5 + 0.5 * sin(dot(q, float2(0.83, -0.55)) * 1.4
                                                   + f * 0.85 + t * 0.30), 1.5);

  return spow(bright, 1.1) * (0.30 + punch * 0.22)
       + spow(bright, 3.0) * (0.20 + along * 0.58 + punch * 0.34)
       + spow(bright, 8.0 - punch * 3.2) * along * (0.62 + focus * 0.55 + punch * 0.80);
}

float depthBand(float d) {
  return clamp(0.04 + smoothStep(1.5, 28.0, d) * 0.92, 0.0, 1.0);
}

float3 fathom(float2 uv, float2 st) {
  float t = u_flow * 0.11;

  float3 ro = float3(0.0, 0.0, 0.0);
  float3 rd = normalize(float3(uv.x * 1.25, uv.y * 1.25 - 0.17, 1.0));

  float floorY = -0.95;
  float surfY = 2.30;

  float3 band = float3(specSlow(0.10), specSlow(0.45), specSlow(0.80));

  float focus = clamp(u_kick * 0.70 + u_snare * 0.30, 0.0, 1.0);

  float punch = power();

  float3 sun = normalize(float3(-0.34, 1.00, 0.32));
  float toSurface = (surfY - floorY) / sun.y;

  float3 col = float3(0.0);

  float tFloor = rd.y < -0.002 ? floorY / rd.y : 1e5;
  float tTop = rd.y > 0.002 ? surfY / rd.y : 1e5;

  float reach = 0.14 + u_swell * 0.36 + u_dynamics * 0.10 + u_section * 0.26;

  if (tFloor < 44.0) {
    float3 hit = ro + rd * tFloor;
    float2 q = hit.xz;

    float bandHere = depthBand(tFloor);
    float sustainHere = specSpread(bandHere);
    float litHere = sustainHere * 0.75 + spec(bandHere) * 0.25;

    float ripple = fbm3(q * 1.55 + float2(0.0, -t * 0.05));
    float2 lit = q + sun.xz * toSurface;
    float c = net(lit, t, band, focus, punch);

    float open = reach * (0.45 + sustainHere * 1.10);
    float pool = smoothStep(0.58 - open * 0.40, 0.86 - open * 0.30,
                            fbm3(lit * 0.26 + float2(-t * 0.020, t * 0.013)));
    float haze = exp(-tFloor * 0.20);

    col += world(0.09 + ripple * 0.18 + u_centroid * 0.08)
         * (0.014 + ripple * 0.030) * haze * (0.35 + pool * 0.65);

    col += world(0.70 + clamp(c, 0.0, 1.0) * 0.28) * c * haze
         * (0.45 + pool * 1.00)

         * (0.10 + litHere * 0.50 + u_level * 0.18 + u_section * 0.10);
  }

  col += world(0.40 + u_centroid * 0.20) * smoothStep(-0.02, 0.50, rd.y)
       * (0.008 + u_level * 0.035 + u_swell * 0.020);

  float far = min(min(tFloor, tTop), 30.0);
  float jitter = hash21(st * 419.0);
  float3 shafts = float3(0.0);
  const int STEPS = 20;
  for (int i = 0; i < STEPS; i++) {
    float s = (float(i) + jitter) / float(STEPS);

    float dist = 0.4 + s * s * far;
    float3 at = ro + rd * dist;
    float2 pr = at.xz + sun.xz * ((surfY - at.y) / sun.y);
    float v = net(pr, t, band, focus, punch) * exp(-dist * 0.15) * exp(-(surfY - at.y) * 0.13);
    float bd = depthBand(dist);
    shafts += world(0.42 + bd * 0.34) * v * (0.07 + specSpread(bd) * 0.55 + spec(bd) * 0.22);
  }
  shafts /= float(STEPS);

  col += shafts * (0.08 + reach * 0.70 + u_level * 0.28);

  float2 grid = uv * 38.0 + float2(t * 0.6, -t * 0.25);
  float2 id = floor(grid);
  float2 k = hash22(id + 31.0);
  float mote = smoothStep(0.12, 0.0, length(fract(grid) - 0.5 - (k - 0.5) * 0.6)) * step(0.86, k.x);
  float inLight = clamp(dot(shafts, float3(0.33)) * 6.0, 0.0, 1.0);
  col += world(0.88) * mote * inLight * (0.06 + u_hat * 0.70 + u_section * 0.10);

  return col;
}


float3 sea(float2 p, float t, float3 band, float pump) {
  float lo = (0.45 + band.x * 1.15) * pump;
  float mid = (0.45 + band.y * 1.15) * pump;
  float hi = (0.45 + band.z * 1.15) * pump;

  float h = 0.0;
  float2 g = float2(0.0);

  float2 d0 = float2( 0.9997,  0.0262); float k0 =  1.90; float a0 = 1.00 * lo;
  float2 d1 = float2( 0.9613,  0.2756); float k1 =  2.90; float a1 = 0.78 * lo;
  float2 d2 = float2( 0.9781, -0.2079); float k2 =  4.30; float a2 = 0.58 * mid;
  float2 d3 = float2( 0.8988,  0.4384); float k3 =  6.10; float a3 = 0.42 * mid;
  float2 d4 = float2( 0.9336, -0.3584); float k4 =  8.40; float a4 = 0.30 * hi;
  float2 d5 = float2( 0.8480,  0.5299); float k5 = 11.60; float a5 = 0.21 * hi;

  float s0 = dot(p, d0) * k0 - t * sqrt(k0) * 0.50;
  float s1 = dot(p, d1) * k1 - t * sqrt(k1) * 0.50;
  float s2 = dot(p, d2) * k2 - t * sqrt(k2) * 0.50;
  float s3 = dot(p, d3) * k3 - t * sqrt(k3) * 0.50;
  float s4 = dot(p, d4) * k4 - t * sqrt(k4) * 0.50;
  float s5 = dot(p, d5) * k5 - t * sqrt(k5) * 0.50;

  h = a0*sin(s0) + a1*sin(s1) + a2*sin(s2) + a3*sin(s3) + a4*sin(s4) + a5*sin(s5);
  g = a0*k0*cos(s0)*d0 + a1*k1*cos(s1)*d1 + a2*k2*cos(s2)*d2
    + a3*k3*cos(s3)*d3 + a4*k4*cos(s4)*d4 + a5*k5*cos(s5)*d5;

  float norm = 1.0 / (a0 + a1 + a2 + a3 + a4 + a5 + 1e-4);
  return float3(h * norm, g * norm);
}

float3 crown(float2 p, float amount) {
  float env = u_kick;
  if (env < 0.003) return float3(0.0);
  float2 origin = float2(sin(u_flow * 0.05) * 1.15, cos(u_flow * 0.043 + 1.7) * 0.85);
  float2 d = p - origin;
  float r = max(length(d), 1e-4);
  float front = (1.0 - env) * 2.4;
  float x = (r - front) * 7.0;
  float e = gauss(x * 0.34) * env;
  float h = sin(x) * e;
  float dh = cos(x) * 7.0 * e + sin(x) * e * (-2.0 * x * 0.34 * 0.34 * 7.0);
  return float3(h, dh * d / r) * amount;
}

float3 room(float3 d) {
  float3 lamp = normalize(float3(0.46, 0.26, 1.0));
  float c = max(dot(normalize(d), lamp), 0.0);

  float3 col = world(0.99) * spow(c, 2600.0) * (4.0 + u_level * 7.0 + u_pulse * 2.0 + power() * 4.0) * (0.45 + u_section * 0.65);
  col += world(0.78 + u_centroid * 0.18) * spow(c, 110.0) * (0.40 + u_level * 1.10 + u_section * 0.60);
  col += world(0.44 + u_centroid * 0.20) * spow(c, 16.0) * (0.020 + u_air * 0.09);

  col += world(0.30 + u_centroid * 0.18) * smoothStep(-0.12, 0.8, d.y)
       * (0.045 + u_swell * 0.070 + u_level * 0.050);
  return col * smoothStep(-0.30, 0.0, d.y);
}

float3 quicksilver(float2 uv, float2 st) {
  float t = u_flow;

  float3 ro = float3(0.0, 0.40, 0.0);
  float3 rd = normalize(float3(uv.x * 1.15, uv.y * 1.15 - 0.26, 1.0));

  if (rd.y > -0.004) return room(rd);

  float dist = -ro.y / rd.y;
  float3 hit = ro + rd * dist;
  float2 p = hit.xz;

  float3 band = float3(specSpread(0.10), specSpread(0.45), specSpread(0.80));

  float pump = 0.28 + clamp(u_kick * 0.62 + u_snare * 0.30 + u_level * 0.45, 0.0, 0.95);

  float near = exp(-dist * 0.14);

  float pw = power();
  float amp = (0.036 + u_level * 0.145 + u_swell * 0.075 + pw * 0.075 + u_section * 0.050) * pump * near
            * (0.50 + u_section * 0.75);

  float3 lat = sea(p, t, band, pump);
  float3 ring = crown(p, 0.010 + u_kick * 0.030) * near;

  float2 slope = lat.yz * amp + ring.yz;
  float3 n = normalize(float3(-slope.x, 1.0, -slope.y));

  float3 view = -rd;
  float3 refl = reflect(rd, n);

  float fres = 0.05 + 0.95 * spow(1.0 - max(dot(view, n), 0.0), 4.5);

  float3 col = room(refl) * fres;

  col += world(0.14 + u_centroid * 0.12) * (1.0 - fres)
       * (0.030 + u_level * 0.110 + spow(clamp(lat.x * 0.5 + 0.5, 0.0, 1.0), 2.0) * 0.160 * near);

  col *= exp(-dist * 0.055);
  col += world(0.30 + u_centroid * 0.16) * spow(1.0 - near, 8.0) * (0.010 + u_swell * 0.030);

  return col;
}


float coronaNoise(float2 p, float period) {
  float2 i = floor(p);
  float2 f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  float x0 = glmod(i.x, period);
  float x1 = glmod(i.x + 1.0, period);
  return mix(mix(hash21(float2(x0, i.y)), hash21(float2(x1, i.y)), f.x),
             mix(hash21(float2(x0, i.y + 1.0)), hash21(float2(x1, i.y + 1.0)), f.x), f.y);
}

float coronaStreams(float turn, float rho, float t) {
  float u = turn * 13.0 + rho * 0.22;
  float v = rho * 1.25 - t * 0.50;
  return coronaNoise(float2(u, v), 13.0) * 0.50
       + coronaNoise(float2(u * 3.0 + 3.1, v * 1.3 - t * 0.19), 39.0) * 0.30
       + coronaNoise(float2(u * 7.0 + 7.7, v * 1.6 - t * 0.33), 91.0) * 0.20;
}

float3 corona(float2 uv, float2 st) {
  float t = u_flow;
  float px = 1.0 / u_resolution.y;
  const float R = 0.165;

  float r = length(uv);
  float turn = atan2(uv.y, uv.x) / TAU + 0.5 + t * 0.0025;
  float h = max(r - R, 0.0);
  float rho = log(max(r, R) / R);

  float reg = clamp(rho / 1.25, 0.0, 1.0);
  float sustain = specBands(reg);
  float lit = specBandsFast(reg);

  float helmets = coronaNoise(float2(turn * 5.0, t * 0.018 + u_seed * 3.7), 5.0);
  float petals = 0.10 + 2.3 * helmets * helmets * helmets;
  float streams = coronaStreams(turn, rho, t);
  float structure = spow(smoothStep(0.30, 0.78, streams), 1.4) * petals;

  float reach = 0.17 + u_swell * 0.10 + u_section * 0.10;
  float body = exp(-h / reach);
  float tail = spow(R / max(r, R), 1.5);
  float tone = clamp(0.30 + 0.62 * exp(-rho * 1.4) + streams * 0.08 + u_centroid * 0.10 + u_section * 0.08, 0.0, 1.0);

  float3 col = float3(0.0);

  col += world(tone) * structure * body * (0.30 + sustain * 0.70 + lit * 0.35 + u_level * 0.20) * (0.40 + u_section * 0.70);
  col += world(tone * 0.85) * structure * tail * (0.05 + sustain * 0.25 + u_swell * 0.06);

  float inner = exp(-h / 0.026);
  col += world(0.90) * inner * (0.25 + 0.75 * structure)
       * (0.24 + specBands(0.0) * 0.45 + u_kick * 1.20 + u_pulse * 0.15);

  col += world(0.64) * gauss(h / (0.0034 + px)) * (0.18 + u_kick * 1.60 + power() * 0.35);

  float fine = coronaNoise(float2(turn * 110.0, rho * 2.2 - t * 0.8), 110.0);
  float resolvable = smoothStep(0.8, 3.0, TAU * r / 110.0 / px);
  col += world(0.80) * spow(fine, 6.0) * resolvable * body * petals
       * (0.04 + u_hat * 0.55 + u_air * 0.20);

  float arc = TAU * R;
  for (int i = 0; i < 3; i++) {
    float k = float(i);
    float at = fract(u_seed * (0.237 + k * 0.119) + k * 0.331);
    float along = (fract(turn - at + 0.5) - 0.5) * arc;
    float width = 0.010 + hash11(k + u_seed) * 0.012;
    float tall = 0.016 + hash11(k * 3.1 + u_seed) * 0.020;
    float lick = coronaNoise(float2(along * 70.0, h * 55.0 - t * 1.1), 1000.0);
    float tongue = gauss(along / width) * exp(-h / tall) * (0.45 + 0.9 * lick);
    col += world(0.70) * tongue * (0.10 + u_snare * 1.30 + u_mid * 0.20);
  }

  float disc = smoothStep(R + px, R - px, r);
  float3 moon = world(0.16) * (0.006 + 0.012 * fbm3(uv * 9.0 + u_seed));
  col = mix(col, moon, disc);

  col += world(0.12 + u_centroid * 0.10) * exp(-r * 2.4) * (0.014 + u_swell * 0.022);
  return col;
}


float2 wickFrame(float2 uv, float t, float width, float tall) {
  const float base = -0.34;
  float y = (uv.y - base) / tall;

  float rise = t * 0.75;
  float bend = (noise(float2(y * 2.1 - rise, u_seed)) - 0.5) * 1.25
             + (noise(float2(y * 4.7 - rise * 1.8, u_seed + 7.3)) - 0.5) * 0.45;
  float lean = clamp(y, 0.0, 1.4);
  return float2(uv.x / width - bend * lean * lean * 0.9, y);
}

float3 wick(float2 uv, float2 st) {
  float t = u_flow;
  const float base = -0.34;

  float weight = specSlow(0.10) * 0.6 + specSlow(0.05) * 0.4;
  float width = 0.096 + weight * 0.020;
  float tall = 0.50 + u_swell * 0.08 + u_section * 0.08;
  float2 q = wickFrame(uv, t, width, tall);

  float y = q.y;
  float bowl = sqrt(max(1.0 - spow(abs(y - 0.24) / 0.30, 2.0), 0.0));
  float taper = spow(max(1.0 - (y - 0.24) / 0.76, 0.0), 0.85);
  float profile = mix(bowl, taper, smoothStep(0.20, 0.28, y)) * 0.60;
  float across = abs(q.x) / max(profile, 0.015);
  float envelope = gauss(across * 1.1) * smoothStep(-0.06, 0.02, y) * smoothStep(1.02, 0.62, y);

  float streak = fbm3(float2(q.x * 1.4, y * 2.6 - t * 1.1) + u_seed);

  float reg = clamp(y, 0.0, 1.0);
  float sustain = specBands(reg);
  float lit = specBandsFast(reg);

  float3 col = float3(0.0);

  float tone = clamp(0.34 + y * 0.40 + envelope * 0.20 + u_centroid * 0.08 + u_section * 0.06, 0.0, 1.0);
  col += world(tone) * envelope * (0.60 + streak * 0.50) * (0.50 + u_section * 0.55)
       * (0.42 + sustain * 1.00 + lit * 0.40 + u_level * 0.30);

  float core = gauss(across * 1.9) * gauss((y - 0.32) / 0.22) * smoothStep(-0.02, 0.10, y);
  col += world(0.98) * core * (0.36 + u_kick * 1.25 + u_pulse * 0.15 + power() * 0.30);

  float cone = gauss(across * 2.6) * gauss((y - 0.06) / 0.08);
  col *= 1.0 - cone * 0.70;

  float rim = gauss((across - 1.0) / 0.25) * smoothStep(-0.02, 0.08, y) * smoothStep(1.0, 0.45, y);
  col += world(0.84) * rim * (0.025 + u_snare * 0.50);

  float2 w = uv - float2(0.0, base - 0.012);
  float stick = gauss(w.x / 0.0030) * smoothStep(0.040, 0.0, abs(w.y + 0.014));
  col = mix(col, float3(0.004), stick * 0.85);
  col += world(0.62) * gauss(length(w - float2(0.0, 0.012)) / 0.006) * (0.30 + u_kick * 0.45);

  float2 centre = uv - float2(0.0, base + tall * 0.34);
  float d = length(centre * float2(1.0, 0.75));
  col += world(0.60 + u_centroid * 0.10) * exp(-d * 4.4) * (0.05 + u_level * 0.08 + u_kick * 0.16 + u_section * 0.08);
  col += world(0.32) * exp(-d * 1.7) * (0.018 + u_swell * 0.030 + u_section * 0.030);

  float above = uv.y - (base + tall * 0.85);
  float2 cell = float2(uv.x * 30.0, uv.y * 30.0 - t * 2.4);
  float2 id = floor(cell);
  float2 f = fract(cell) - 0.5;
  float2 k = hash22(id);
  float drift = (noise(float2(id.y * 0.37, u_seed)) - 0.5) * 0.9;
  float ember = smoothStep(0.10, 0.0, length(f - (k - 0.5) * 0.5 - float2(drift, 0.0)))
              * step(0.90, k.y);
  float plume = gauss(uv.x / (0.03 + max(above, 0.0) * 0.45)) * smoothStep(-0.02, 0.06, above)
              * exp(-max(above, 0.0) * 3.2);

  col += world(0.80) * ember * plume * (0.04 + u_section * 0.22 + u_hat * 1.4 + u_air * 0.3);
  return col;
}


float borealShore(float bearing, float elevation, float px) {

  if (elevation > 0.065) return 0.0;
  float hills = 0.006 + 0.016 * fbm3(float2(bearing * 1.8 + u_seed, 0.5));
  float cover = smoothStep(hills + px, hills - px, elevation);
  const float SPACING = 0.016;
  float cell = floor(bearing / SPACING);
  float up = elevation - hills;
  for (int j = -2; j <= 2; j++) {
    float id = cell + float(j);
    float stand = noise(float2(id * SPACING * 6.0, u_seed * 5.0));
    float kind = hash11(id * 1.37 + 5.0);
    if (kind > stand * 1.3) continue;
    float centre = (id + hash11(id * 2.11 + 1.0)) * SPACING;
    float height = (0.012 + 0.040 * hash11(id * 3.7 + 2.0)) * (0.5 + stand * 0.9);
    float tier = 0.45 + 0.55 * fract(up * (150.0 + kind * 60.0) + kind * 3.0);
    float reach = max(height - up, 0.0) * (0.15 + kind * 0.06) * tier + 0.0006;
    cover = max(cover, smoothStep(-px, px, reach - abs(bearing - centre)) * step(up, height));
  }
  return cover;
}

float borealFold(float u, float t, float seed) {
  return 1.25 * sin(0.40 * u - t * 0.17 + seed * 3.0)
       + 0.50 * sin(1.10 * u + t * 0.12 + seed * 1.7);
}

float3 borealSky(float3 d, float t, float px, float3 bands) {
  float level = max(length(d.xz), 1e-4);
  float bearing = d.x / d.z;
  float elevation = d.y / level;

  float3 col = world(0.14 + u_centroid * 0.06) * (0.012 + 0.070 * exp(-elevation * 5.0))
           * (0.8 + u_level * 0.4 + u_swell * 0.3);

  float milky = gauss((elevation * 0.95 + bearing * 0.50 - 0.42) / 0.20);
  if (milky > 0.02) {
    float clouds = fbm3(float2(bearing, elevation) * 5.0 + u_seed * 1.3);
    col += mix(float3(0.55, 0.60, 0.72), world(0.30), 0.35) * milky * spow(clouds, 2.2) * 0.060;
  }

  for (int layer = 0; layer < 2; layer++) {
    float scale = layer == 0 ? 90.0 : 210.0;
    float2 cell = float2(bearing, elevation) * scale;
    float2 id = floor(cell);
    float2 k = hash22(id + 17.0 + float(layer) * 51.0);
    float chance = layer == 0 ? 0.935 : 0.90 - milky * 0.12;
    float star = smoothStep(0.17, 0.0, length(fract(cell) - 0.5 - (k - 0.5) * 0.6)) * step(chance, k.x);
    float glint = 0.5 + 0.5 * sin(u_time * (1.3 + k.y * 2.1) + k.y * 40.0);

    float bright = (layer == 0 ? 0.20 + k.y * 0.45 : 0.07 + k.y * 0.10) * (1.25 - u_section * 0.55);
    col += float3(0.85, 0.88, 1.0) * star * bright * (0.55 + glint * 0.45 + u_hat * 0.9);
  }

  const float FOOT = 1.35;
  float tall = 1.4 + u_swell * 0.6 + u_section * 0.9;
  float3 light = float3(0.0);
  float glow = 0.0;
  float before0 = 0.0;
  float before1 = 0.0;
  float zBefore = 1.0;
  const int STEPS = 40;
  for (int i = 0; i <= STEPS; i++) {
    float z = 1.0 * exp(float(i) * 0.096);
    float3 p = d * (z / d.z);
    if (i > 0 && p.y - FOOT * 1.9 > tall * 3.2) break;

    for (int c = 0; c < 2; c++) {
      float seed = float(c) * 4.7;

      float2 origin = c == 0 ? float2(-3.2, 0.6) : float2(-5.8, 2.9);
      float2 along = normalize(float2(0.85, 1.0));
      float foot = c == 0 ? FOOT : FOOT * 1.9;
      float2 across = float2(-along.y, along.x);
      float off = dot(p.xz - origin, across) - borealFold(dot(p.xz - origin, along), t, seed);
      float before = c == 0 ? before0 : before1;
      if (c == 0) before0 = off; else before1 = off;
      if (i == 0) continue;

      float haze = exp(-z * 0.045) * (c == 0 ? 1.0 : 0.80 * smoothStep(0.25, 0.75, u_section));
      float h = p.y - foot;

      float near = gauss(off / ((z - zBefore) * 0.9));
      if (near > 0.004) glow += near * (h > 0.0 ? exp(-h / tall) : exp(h * 6.0)) * haze;

      if (before * off > 0.0) continue;

      float f = before / (before - off);
      float zc = mix(zBefore, z, f);
      float3 pc = d * (zc / d.z);
      float hc = pc.y - foot;
      float u = dot(pc.xz - origin, along);
      float slant = (z - zBefore) / max(abs(off - before), 1e-3);

      float weight = slant / (1.0 + 0.12 * slant * slant);
      float enter = smoothStep(0.0, 5.0, u);

      float footprint = zc * px;
      float fine = smoothStep(0.9, 0.3, footprint * 16.0);
      float rays = noise(float2(u * 5.5 - t * 0.9, hc * 0.35 + seed)) * (1.0 - 0.45 * fine)
                 + noise(float2(u * 16.0 - t * 1.5, hc * 0.7 + seed * 2.0)) * 0.45 * fine;
      float stand = tall * (0.30 + 1.30 * rays * rays);

      float profile = hc > 0.0 ? exp(-hc / stand) : exp(hc * 14.0) + 0.05 * exp(hc * 1.2);

      float surge = 0.25 + 1.35 * spow(noise(float2(u * 0.28 - t * 0.35, seed * 3.0)), 1.4);

      float up = clamp(hc / (tall * 1.4), 0.0, 1.0);
      float sustain = up < 0.5 ? mix(bands.x, bands.y, up * 2.0) : mix(bands.y, bands.z, up * 2.0 - 1.0);
      float streaks = 0.40 + spow(rays, 2.2 + u_snare * 2.0) * (2.0 + u_snare * 1.5);

      float fringe = exp(-abs(hc) / 0.08) * (0.34 + u_kick * 1.60 + power() * 0.25);
      float tone = mix(0.44, 0.84, up) + u_centroid * 0.06;

      light += (world(tone) * profile * streaks * (0.35 + sustain * 0.90 + u_level * 0.20)
              + world(0.97) * fringe * streaks)
             * weight * surge * enter * haze * (1.0 + power() * 0.4);
    }
    zBefore = z;
  }
  col += (light * 0.56 + world(0.58) * glow * 0.028) * (0.45 + u_section * 0.60);

  col += world(0.52) * exp(-max(elevation, 0.0) * 22.0) * (0.035 + u_level * 0.04 + u_swell * 0.03);

  float land = borealShore(bearing, elevation, px);
  return mix(col, float3(0.002), land);
}

float3 boreal(float2 uv, float2 st) {
  float t = u_flow;
  float px = 1.15 / u_resolution.y;

  float3 rd = normalize(float3(uv.x * 1.15, uv.y * 1.15 + 0.21, 1.0));

  float3 bands = float3(specSpread(0.10), specSpread(0.45), specSpread(0.80));

  if (rd.y >= 0.0) return borealSky(rd, t, px, bands);

  float below = -rd.y;
  float reach = 0.08 / below;
  float2 w = rd.xz * reach;
  float ripple = noise(float2(w.x * 2.2 + t * 0.10, w.y * 0.8 - t * 0.28))
               + noise(float2(w.x * 5.3 - t * 0.07, w.y * 1.9 - t * 0.41)) * 0.5 - 0.75;
  float calm = smoothStep(0.0, 0.25, below);
  float3 mirrored = normalize(float3(rd.x + ripple * 0.030 * calm, below + ripple * 0.022 * calm, rd.z));
  float fresnel = 0.45 + 0.40 * exp(-below * 6.0);
  float3 col = borealSky(mirrored, t, px, bands) * fresnel;
  return col + world(0.10) * 0.006;
}
float3 scene(int effect, float2 uv, float2 st) {
 switch(effect) {
case 0: return veil(uv, st);
case 1: return bloom(uv, st);
case 2: return coil(uv, st);
case 3: return ink(uv, st);
case 4: return harp(uv, st);
case 5: return fathom(uv, st);
case 6: return quicksilver(uv, st);
case 7: return corona(uv, st);
case 8: return wick(uv, st);
case 9: return boreal(uv, st);
default: return veil(uv, st);
}
}

float3 aces(float3 x) {
  return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

float4 render(float2 position, int effect) {
  preparePalette();
  float2 st = position / u_resolution;
  float2 uv = (position - 0.5 * u_resolution) / u_resolution.y;

  float3 col = scene(effect, uv, st);

  float2 v = st - 0.5;
  float vignette = 1.0 - dot(v, v) * (0.62 - u_level * 0.12);
  col *= clamp(vignette, 0.0, 1.0);

  col = mix(col, aces(col), 0.88);

  float g = hash21(position + fract(u_time) * 419.0) - 0.5;
  float luma = dot(col, float3(0.2126, 0.7152, 0.0722));
  col += g * u_grain * mix(0.055, 0.012, smoothStep(0.0, 0.35, luma));

  float dither = (hash21(position * 1.37 + 11.0) - 0.5) / 255.0;
  col += dither;

  return float4(max(col, float3(0.0)), u_alpha);
}
};
struct VertexOut { float4 position [[position]]; };
vertex VertexOut fullScreen(uint id [[vertex_id]]) {
    float2 p = float2((id << 1) & 2, id & 2);
    return {float4(p * 2.0 - 1.0, 0.0, 1.0)};
}
// Each effect is its own specialised pipeline. With the effect as a runtime
// argument, every effect was compiled for the register pressure of the
// heaviest one; as a function constant, the other branches are removed.
constant int effectIndex [[function_constant(0)]];
fragment float4 visualizer(VertexOut in [[stage_in]],
                           constant float* uniforms [[buffer(0)]],
                           texture2d<float> spectrum [[texture(0)]],
                           texture2d<float> historyTexture [[texture(1)]]) {
    Instrument instrument {uniforms, spectrum, historyTexture};
    return instrument.render(float2(in.position.x, uniforms[1] - in.position.y), effectIndex);
}
